# Use Node.js base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy NestJS project files
COPY ../../server/package*.json ./
RUN npm install

# Copy the rest of the server code
COPY ../../server .

# Expose port for the API
EXPOSE 3000

# Start the NestJS server in watch mode for local development
CMD ["npm", "run", "start:dev"]
